### PR TITLE
TODO: added `op_checksigadd` to `op_codes`

### PR DESCRIPTION
**Pull request by AdvaitPote**
As per the newly added TODO, I have added `OP_CHECKSIGADD` to `op_codes`.

### CODE REVIEW

**Comment by karask** [comment]
Hi @AdvaitPote, 

Unfortunately this is not that simple. That opcode is only valid for taproot. There are other differences as well. They all need to be group appropriately and checked only for tapscripts.

**Comment by AdvaitPote** [comment]
Yes, you did mention in the TODO that some other tapscript changes would need to be made. So would these opcodes need to be added elsewhere along with some tapscript functionalities? Unfortunately, in all of the courses we took and our assignment, Taproot was out of scope so I am not much aware of the same. I was thinking we would add these opcodes to `script.py` and then add those same tapscript reading features in the `Script` class itself.

**Comment by karask** [comment]
I  believe it would be cleaner if completely new dicitionaries should be used for tapscript (if the changes are many it could be a new file tapscript.py, otherwise it could go into script). Then if the specific tx's output is segwit v1 consult the new dictionary for the opcodes, otherwise use the current dictionaries.

**Comment by AdvaitPote** [comment]
Makes sense! Making a new `Tapscript` class or a `tapscript.py` would be helpful too because as more updates will be made, managing them in a separate file would be more convenient.

**Comment by karask** [comment]
I am closing this for. Re-open if you want to work on it.

**Pull request closed without merging**
