### PR TITLE
TODO: rename to Secp256k1Params

### PR DESCRIPTION
**Pull request by iamhardikat11**
Just a Bit of Cleaning done in [bitcoinutils/utils.py](https://github.com/karask/python-bitcoin-utils/blob/master/bitcoinutils/utils.py)

Solved:-
TODO REMOVE --- NOT USED
TODO improve by checking if valid, etc.
TODO Implement is_address_bech32()
TODO name hex_to_bytes ??

### CODE REVIEW

**Comment by iamhardikat11** [comment]
TODO TEMP scripts is just the top root th_branch manually calculated!
Done! Please Check

**Comment by karask** [comment]
Hi @iamhardikat11 

Wrt hex_to_bytes: if hex_to_bytes(..., False) is not called anywhere (which I believe it is the case, but please check) then we can use h_to_b instead and delete hex_to_bytes entirely.

Wrt to calculating the merkle proof I have not checked it in detail yet but I saw that you don't use tagged hashes (see taproot examples, where I manually construct it). Have you run the tests after the change to see if anything breaks?

**Comment by iamhardikat11** [comment]
Hi @karask I have run the tests and then pass on the PR I made. I will try and see to apply the changes you suggested above.

**Comment by karask** [comment]
Taproot example: https://github.com/karask/python-bitcoin-utils/blob/master/examples/spend_p2tr_three_scripts_by_script_path.py

It would be better if each PR was a specific feature. I could merge the clean up of h_to_b but now I cannot because of the merkle proof :-)

**Comment by iamhardikat11** [comment]
Ok

**Comment by iamhardikat11** [comment]
HI @karask I have removed Merkle Root Proof, you can merge the PR if everything else is fine.

**Comment by iamhardikat11** [comment]
Hi @karask I have done a cleanup task from TODO to remove bytes32_from_int and changed every occurence to i_to_b32. 
All tests passed 
...................................................................
----------------------------------------------------------------------
Ran 67 tests in 9.165s

OK

**Pull request merged**
