### PR TITLE
Add locktime version transaction

### PR DESCRIPTION
**Pull request by rramakrishnan246**
add locktime and version to deserialization of Transaction object

### CODE REVIEW

**Comment by rramakrishnan246** [comment]
@karask I wanted to put this PR on top of my other pr but do not see the option to do so here, but this should be stacked on top (or we can just merge this one). The test should cover dealing with this as well if we specify a locktime in the Transaction object.

If this looks good can we also release a new version after this so we can use it

**Comment by karask** [comment]
Hi and thanks for the PR. 

There is a Locktime object (in transaction.py). Please use Locktime.for_transaction() when you specify the locktime in the example.

Just commit on top I will merge. Thanks.

**Comment by rramakrishnan246** [comment]
added a minor test fix because if we enable segwit without providing witnesses for now serialization fails

**Comment by karask** [comment]
Thank you @rramakrishnan246 

If you are interested there are tons of TODOs if you would like to contribute. I could create digestible issues that can be worked individually if you are interested.

**Comment by rramakrishnan246** [comment]
Do we need to do anything to release the latest version beyond just merging here?

Currently I need this functionality for some work I am doing, I can definitely work on some tasks if there are any but I do not think I can commit to any timelines for them

**Comment by karask** [comment]
I uploaded the packages to pypi for you to use (0.6.4).

No commitments! It is an open source project... if and when you have time you can contribute. :-)

**Comment by rramakrishnan246** [comment]
awesome thanks - and ya I will definitely contribute in the future when I can

**Pull request merged**
