### PR TITLE
from_raw updated

### PR DESCRIPTION
**Pull request by guptamukund22**
`from_raw `function in **transaction.py** has been updated and now used **struct** library.

### CODE REVIEW

**Comment by karask** [comment]
Hi @guptamukund22 

Tried to run the tests before merging but there was an error. I get wrong arguments on parse_compact_size()

**Comment by karask** [comment]
> Hi @karask Could you specify which test you were running so that I can cross check again. I do not remember seeing any error of such kind. Apologies for it.

It is probably something trivial. Just run ./tests.sh to see the error. I might have time to look at it more tomorrow.

$ ./tests.sh                                   
E...........................parse_compact_size() takes 1 positional argument but 2 were given            
0 162                                                                                                    
.parse_compact_size() takes 1 positional argument but 2 were given                                       
0 162                                                                                                    
Eparse_compact_size() takes 1 positional argument but 2 were given                                       
0 162                                                                                                    
.parse_compact_size() takes 1 positional argument but 2 were given
...

**Comment by guptamukund22** [comment]
Hi @karask 
I have made the changes, the problem with previous code is that I had missed a function to be added in **utils.py** . But now I realized that the function was redundant and parsing everything in bytes would resolve the issue.

**Comment by karask** [comment]
Thanks @guptamukund22 !

I noticed that there are still comments with parse_compact_size (line 167), maybe elsewhere. 

Can you explain what the +9 is in lines 564, 574, etc. are? If they include the compact_size (varint) part then it is not always +9, and could be larger.

Same for line 168 where there is a +8. Effectively this applies everywhere a varint is used; can't increase with a hard-coded number. The tests work because there are no tests that include txs with >253 inputs or outputs.

It would be a good idea to add such a test, e.g. with 255 outputs to make sure this is covered in future modifications.

**Comment by guptamukund22** [comment]
Hi @karask ,
About the +9 (in lines 564, 574, etc.) and +8 in line 168, I just took inspiration from the existing code and did not think much about it. But now that you have mentioned it, I believe I need to make appropriate changes. Thanks for mentioning it.

**Pull request merged**
